### ISSUE TITLE
Disposing the Store

### ISSUE THREAD

**Issue by willhausman** [bytecodealliance/wasmtime-dotnet#149]
In `0.39.1-preview2`, I had a test in my project which made sure I could still use an `Instance` after a `Linker` had been disposed. This was just a sanity check to make sure my chosen approach was valid, because I wasn't interested in holding onto a reference to the `Linker` when I no longer needed it.

In `0.40.0-preview1`, the API surface was altered to drop the reference to `store` in the various calls off the `Instance`. This was simpler, and a nice change, but it means I am once again holding onto a reference to an object which I no longer need after creating `Instance`.  However, the lifetime of the store matters to the Instance.  This test fails, despite _looking_ like it should pass:

```csharp
    [Fact]
    public void InstanceRunAfterStoreIsDisposed()
    {
        var expected = 1;
        using var engine = new Engine();
        using var module = Module.FromText(engine, "hello", SampleWat);
        Instance instance;

        using (var store = new Store(engine))
        {
            using var linker = new Linker(engine);

            linker.Define(
                "",
                "hello",
                Function.FromCallback(store, () => expected)
            );

            instance = linker.Instantiate(store, module);
        }

        var result = instance.GetFunction("run")?.Invoke();
        result.Should().Be(expected);
    }

    private const string SampleWat = @"(module
  (import """" ""hello"" (func $.hello (result i32)))
  (func (export ""run"") (result i32) call $.hello))";
```

Perhaps this is simply an artifact of the way I am using the `Store`, but if `0.40.0-preview1` was trying to prevent us from accidentally cross-invoking with the wrong `Store`, does that mean `Store` is only intended to be used by a single `Instance`, and `Instance` should be responsible for disposing of the `Store`?

For the moment, my class is just holding a copy of the `Store` alongside the `Instance` which it can dispose, so I am not hurting for a solution. It just feels odd that I need a reference to this object purely as a mechanism to manage its disposal.

**Comment by peterhuene** [comment]
Indeed, #147 did make the relationship between `Instance` and `Store` implicit, making it harder to decipher how `Store` should be disposed.

The general rule should be: the `Store` should only be explicitly disposed after there is no use of any associated items with the store.

In your test case above, there are three things that are associated with the store:

* The function created with `Function.FromCallback`.
* The linker via the `Linker.Define` method because it keeps a reference to said store-dependent function.
* The instance created with the `Linker.Instantiate` method.

The first two associations could be eliminated by using `Linker.DefineFunction` which defines a store-independent function in the linker. Regardless, the test doesn't keep a reference on the function and the linker gets disposed before the store does, so the first two associations aren't the issue.

As you described, the last association is the issue because the store gets disposed while an instance from that store is still in use.

Regarding your question as to whether or not the instance should dispose the store: it should not as there can be multiple instances in the same store. The change was made to both make the API a little more ergonomic (eliminating a repeated parameter throughout the API) and also makes it impossible to accidentally pass the wrong store.

To verify, though, the behavior you are seeing is an `ObjectDisposedException` when calling `Instance.GetFunction`, correct?

While you don't _need to_ keep a reference on the `Store` because the GC will still clean things up correctly, if you do desire a deterministic release of a `Store` and all of its resources, you'll need to keep a reference to the `Store` around you can explicitly dispose once it is guaranteed that there is no further use of anything from that store.

I currently don't have any ideas on how to improve this experience for developers given the implicit store association.

**Comment by willhausman** [comment]
Thank you. That is the behavior I am seeing, and I do have the ability to explicitly detect when the `Store` should be disposed.  I was not positive that a `Store` could be used with multiple `Instance`s, so leaving it this way does seem correct.

**Comment by peterhuene** [comment]
@willhausman do you think there's anything else needed here before we close this issue? Thanks!

**Comment by willhausman** [comment]
No, @peterhuene. This issue can be closed.
