### ISSUE TITLE
Proposal: Wasmtime 1.0

### ISSUE THREAD

**Issue by alexcrichton** [bytecodealliance/wasmtime-dotnet#75]
I wanted to raise awareness in this repository about the [proposal for Wasmtime to become 1.0](https://github.com/bytecodealliance/rfcs/pull/14#issuecomment-915589031). If others are watching just this repository and are interested to learn what 1.0 would mean for Wasmtime and this embedding, feel free to read over the RFC and leave comments!

**Comment by willhausman** [comment]
While reading through the proposal, one question came to mind. Does the current status of the `wasmtime-dotnet` as a Tier 3 component (and thus less stable) mean that it will not move to 1.0 and out of preview state until it has more contributor support and can move to Tier 1?

**Comment by alexhiggins732** [comment]
Hi @willhausman! Your response here has motivated me to get involved with this repo because it does appear in fact that Microsoft is not internally assigning resources to support wasmtime as a Tier 1 or even Tier 2 product. Unfortunately, from my reading, the RFC doesn't allow for individuals to volunteer to support a repository or a product to make it a Tier 1 or Tier 2 product. Instead my take is there should be a an enterprise funded team that works in lockstep with upstream to coordinate releases every 4 weeks per the RFC. I would certainly like the volunteer but the RFC kind of makes it clear that even though this an open source standard the community at large cannot participate, only enterprises which fund a fully team for their preferred platform and language.

**Comment by peterhuene** [comment]
Wasmtime 1.0.0 was released earlier this week, so I will be preparing a 1.0.0 release today of the `Wasmtime` nuget  package, taking it out of preview at the same time.
