### ISSUE TITLE
How to make a store that uses WASI?

### ISSUE THREAD

**Issue by rygo6** [bytecodealliance/wasmtime-dotnet#83]
So I saw that there is SetWasiConfiguration method, I presume I have to pass something to it in order to enable WASI?

I took a wild guess and just did this:
```
            WasiConfiguration wasiConfiguration = new WasiConfiguration()
                                                    .WithInheritedArgs()
                                                    .WithInheritedArgs()
                                                    .WithInheritedEnvironment()
                                                    .WithInheritedStandardError()
                                                    .WithInheritedStandardInput()
                                                    .WithInheritedStandardOutput();
            m_Store.SetWasiConfiguration(wasiConfiguration);
```

But my `wasi_snapshot_preview1` functions still are not defined. 

Is there any example on how I configure wasmtime to use WASI through dotnet?

**Comment by matt9ucci** [comment]
@rygo6 The [tests/WasiTests.cs](https://github.com/bytecodealliance/wasmtime-dotnet/blob/d48c3215d7ba73bf68c6d18f0a15452c615b5285/tests/WasiTests.cs) would help you?

**Comment by peterhuene** [comment]
You'll also need to call `Linker.DefineWasi` so that the WASI functions get defined as imports to any instances you create.

**Comment by rygo6** [comment]
Thank you, that works. Is there anything that explains what these various args, environment, standard input/output decorators are for? I've not seen these concepts in a WASI context before.

**Comment by peterhuene** [comment]
[`WasiConfiguration`](https://bytecodealliance.github.io/wasmtime-dotnet/api/Wasmtime.WasiConfiguration.html) in the .NET API maps mostly to `WasiCtx` in Wasmtime's Rust API.

It allows you to set up the "WASI environment" for any instantiations in that store.

By default, a WASI configuration doesn't provide any command line arguments, environment variables, or preopened directories (i.e. a map of host file system directory to "virtual" directory inside of WASI). It also redirects stdin/stdout/stderr to, effectively, a null pipe.

So `Linker.DefineWasi` tells Wasmtime to define the WASI functions inside the linker so that modules that import WASI functions can be instantiated and then `Store.SetWasiConfiguration` must then be used to provide a WASI configuration for those runtime-implemented WASI functions defined in the linker.

**Comment by rygo6** [comment]
Thank you that answers all my questions.
