### ISSUE TITLE
Path to wasmtime shared lib in published NuGet packages incorrect for Linux, Windows RIDs

### ISSUE THREAD

**Issue by cgranade** [bytecodealliance/wasmtime-dotnet#86]
Published NuGet packages for wasmtime-dotnet place `wasmtime.dll` and `libwasmtime.so` at `win-x64/native/lib/libwasmtime.dylib/wasmtime.dll` and `linux-x64/native/lib/libwasmtime.dylib/libwasmtime.so` respectively. As a result, P/Invoke calls using the published packages fail to find the required `wasmtime` shared library.

<img width="896" alt="image" src="https://user-images.githubusercontent.com/31516/150927669-84a5652d-510b-425f-946a-7c69e0cc57cf.png">

By contrast, when building the NuGet package locally, the extra `libwasmtime.dylib` entry on the path is removed:

<img width="896" alt="image" src="https://user-images.githubusercontent.com/31516/150927736-619d7730-8dbc-42a5-abba-d69c8ceb169f.png">

**Comment by peterhuene** [comment]
Hi @cgranade. It looks like this was broken ever since we moved this out of the `wasmtime` repo and into the `wasmtime-dotnet` repo. I'm honestly surprised by this, but perhaps there aren't enough windows/linux users to have noticed.

I'll put a fix up immediately and release a fixed 0.33.0 package.
